name: ${project.parent.name}
version: ${project.parent.version}
description: ${project.description}
author: Gecolay
website: https://www.spigotmc.org/resources/62325
main: dev.geco.gsit.GSitMain
api-version: 1.13
folia-supported: true
softdepend: [GriefPrevention, PlaceholderAPI, PlotSquared, WorldGuard]

commands:

  gsit:

    usage: /<command>
    aliases: [sit]
    description: Sit-Command

  glay:

    usage: /<command>
    aliases: [lay]
    description: Lay-Command

  gbellyflop:

    usage: /<command>
    aliases: [bellyflop]
    description: BellyFlop-Command

  gspin:

    usage: /<command>
    aliases: [spin]
    description: Spin-Command

  gcrawl:

    usage: /<command>
    aliases: [crawl]
    description: Crawl-Command

  gemote:

    usage: /<command>
    aliases: [emote]
    description: Emote-Command

  gsitreload:

    usage: /<command>
    aliases: [gsitrl]
    description: Plugin-Reload



permissions:

  GSit.*:
    default: op
    description: OP-Permission for all commands and features of GSit
    children:
      GSit.Sit.*: true
      GSit.PlayerSit.*: true
      GSit.Pose.*: true
      GSit.Emote.*: true
      GSit.Kick.*: true
      GSit.ByPass.*: true
      GSit.Update: true
      GSit.Reload: true

  GSit.Sit.*:
    default: op
    description: Sit | Permission
    children:
      GSit.Sit: true
      GSit.SitClick: true
      GSit.SitToggle: true

  GSit.Sit:
    default: true
    description: Sit command | Permission

  GSit.SitClick:
    default: true
    description: Sit click | Permission

  GSit.SitToggle:
    default: true
    description: Toggle Sit ability | Permission

  GSit.PlayerSit.*:
    default: op
    description: PlayerSit | Permission
    children:
      GSit.PlayerSit: true
      GSit.PlayerSitToggle: true

  GSit.PlayerSit:
    default: true
    description: PlayerSit click | Permission

  GSit.PlayerSitToggle:
    default: true
    description: Toggle PlayerSit ability | Permission

  GSit.Pose.*:
    default: op
    description: Pose | Permission
    children:
      GSit.Lay: true
      GSit.BellyFlop: true
      GSit.Spin: true
      GSit.Crawl.*: true

  GSit.Lay:
    default: true
    description: Lay command | Permission

  GSit.BellyFlop:
    default: true
    description: BellyFlop command | Permission

  GSit.Spin:
    default: true
    description: Spin command | Permission

  GSit.Crawl.*:
    default: op
    description: Crawl | Permission
    children:
      GSit.Crawl: true
      GSit.Crawl.CrawlToggle: true

  GSit.Crawl:
    default: true
    description: Crawl command | Permission

  GSit.CrawlToggle:
    default: true
    description: Toggle Crawl ability | Permission

  GSit.Emote.*:
    default: true
    description: Emote | Permission
    children:
      GSit.Emote: true

  GSit.Emote:
    default: true
    description: Emote command | Permission

  GSit.Kick.*:
    default: op
    description: Kick | Permission
    children:
      GSit.Kick.Sit: true
      GSit.Kick.Pose: true

  GSit.Kick.Sit:
    default: op
    description: Kick sit | Permission

  GSit.Kick.Pose:
    default: op
    description: Kick pose | Permission

  GSit.ByPass.*:
    default: op
    description: ByPass | Permission
    children:
      GSit.ByPass.World: true
      GSit.ByPass.Region: true

  GSit.ByPass.World:
    default: op
    description: ByPass world | Permission

  GSit.ByPass.Region:
    default: op
    description: ByPass region | Permission

  GSit.Update:
    default: op
    description: Update notification | Permission

  GSit.Reload:
    default: op
    description: Plugin reload command | Permission