name: ${project.parent.name}
version: ${project.parent.version}
description: ${project.description}
author: Gecolay
website: https://www.spigotmc.org/resources/62325
main: dev.geco.gsit.GSitMain
api-version: 1.13
softdepend: [PlaceholderAPI, WorldGuard]

commands:

  gsit:

    usage: /<command>
    aliases: [sit]
    description: Sit-Command

  glay:

    usage: /<command>
    aliases: [lay]
    description: Lay-Command

  gbellyflop:

    usage: /<command>
    aliases: [bellyflop]
    description: BellyFlop-Command

  gspin:

    usage: /<command>
    aliases: [spin]
    description: Spin-Command

  gcrawl:

    usage: /<command>
    aliases: [crawl]
    description: Crawl-Command

  gemote:

    usage: /<command>
    aliases: [emote]
    description: Emote-Command

  gsitreload:

    usage: /<command>
    aliases: [gsitrl]
    description: GSit-Config-Reload
    permission: GSit.GSitReload



permissions:

  GSit.*:
    default: op
    description: OP-Permission for all Commands and Functions for GSit
    children:
      GSit.Sit: true
      GSit.SitClick: true
      GSit.SitToggle: true
      GSit.PlayerSit: true
      GSit.PlayerSitToggle: true
      GSit.Lay: true
      GSit.BellyFlop: true
      GSit.Spin: true
      GSit.Crawl: true
      GSit.Emote: true
      GSit.Kick.*: true
      GSit.ByPass.*: true
      GSit.Update: true
      GSit.GSitReload: true

  GSit.Sit:
    default: true
    description: Sit | Permission

  GSit.SitClick:
    default: true
    description: Sit Click | Permission

  GSit.SitToggle:
    default: true
    description: Toggle Sit-Ability | Permission

  GSit.PlayerSit:
    default: true
    description: PlayerSit | Permission

  GSit.PlayerSitToggle:
    default: true
    description: Toggle PlayerSit-Ability | Permission

  GSit.Lay:
    default: op
    description: Lay | Permission

  GSit.BellyFlop:
    default: op
    description: BellyFlop | Permission

  GSit.Spin:
    default: op
    description: Spin | Permission

  GSit.Crawl:
    default: op
    description: Crawl | Permission

  GSit.Emote:
    default: op
    description: Emote | Permission

  GSit.Kick.*:
    default: op
    description: Kick | Permission
    children:
      GSit.Kick.Sit: true
      GSit.Kick.Pose: true

  GSit.Kick.Sit:
    default: op
    description: Kick Sit | Permission

  GSit.Kick.Pose:
    default: op
    description: Kick Pose | Permission

  GSit.ByPass.*:
    default: op
    description: ByPass | Permission
    children:
      GSit.ByPass.World: true

  GSit.ByPass.World:
    default: op
    description: ByPass World | Permission

  GSit.Update:
    default: op
    description: Get-Update-Notification | Permission

  GSit.GSitReload:
    default: op
    description: Config-Reload-Command | Permission